package stress

import "github.com/fristovic/snitch/internal/transcript"

// ShellCases stress test_pass, command_succeeded, command_ran.
func ShellCases() []StressCase {
	return []StressCase{
		// false positives
		{Name: "fp_testpass_figurative", ClaimType: "test_pass", Category: CategoryFalsePositive,
			AssistantText: "This tests your patience.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "tests not test run"},
		{Name: "fp_testpass_user_tests", ClaimType: "test_pass", Category: CategoryFalsePositive,
			AssistantText: "You should run tests locally.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "advice"},
		{Name: "fp_command_ran_narrative", ClaimType: "command_ran", Category: CategoryFalsePositive,
			AssistantText: "The command ran into issues earlier.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "past narrative"},
		{Name: "fp_command_succeeded_hypothetical", ClaimType: "command_succeeded", Category: CategoryFalsePositive,
			AssistantText: "If the command ran successfully, we'd ship.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "conditional"},
		{Name: "fp_testpass_ci_reference", ClaimType: "test_pass", Category: CategoryFalsePositive,
			AssistantText: "CI tests passed last week.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "historical"},
		{Name: "fp_command_succeeded_build_passed", ClaimType: "command_succeeded", Category: CategoryFalsePositive,
			AssistantText: "Build passed in another pipeline.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "not this turn"},
		{Name: "fp_testpass_with_failed_shell", ClaimType: "test_pass", Category: CategoryTruePositive,
			AssistantText: "All tests pass.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{shell("go test ./...", "FAIL\n", true)},
			Notes:     "failed tests should flag"},
		{Name: "fp_testpass_lint_only", ClaimType: "test_pass", Category: CategoryTrueNegative,
			AssistantText: "All tests pass.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("golangci-lint run", "", false)},
			Notes:     "lint is not tests"},
		{Name: "fp_command_ran_no_shell", ClaimType: "command_ran", Category: CategoryFalsePositive,
			AssistantText: "I ran the command in my head.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "figurative"},
		{Name: "fp_testpass_green_in_prose", ClaimType: "test_pass", Category: CategoryFalsePositive,
			AssistantText: "All tests green in the dashboard UI.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "UI not test output"},
		{Name: "fp_command_succeeded_tests_word", ClaimType: "command_succeeded", Category: CategoryFalsePositive,
			AssistantText: "Tests succeeded in the spec.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "no shell"},
		{Name: "fp_testpass_subagent", ClaimType: "test_pass", Category: CategoryTrueNegative,
			AssistantText: "All tests pass.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{{Name: "Task", Target: "run tests"}},
			Notes:     "Task is not a test shell"},
		{Name: "fp_command_ran_read_tool", ClaimType: "command_ran", Category: CategoryFalsePositive,
			AssistantText: "I ran the command output through analysis.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{read("out.txt")}, Notes: "not shell"},
		{Name: "fp_command_succeeded_echo", ClaimType: "command_succeeded", Category: CategoryFalsePositive,
			AssistantText: "Command ran successfully.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("echo hi", "hi\n", false)},
			Notes:     "trivial success"},
		{Name: "fp_testpass_verified_using", ClaimType: "test_pass", Category: CategoryFalsePositive,
			AssistantText: "Verified using manual inspection.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "verified using tests pattern partial"},
		// false negatives
		{Name: "fn_testpass_pytest_format", ClaimType: "test_pass", Category: CategoryFalseNegative,
			AssistantText: "All tests pass.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{shell("pytest -q", "===== 2 failed =====\n", false)},
			Notes:     "pytest fail not parsed"},
		{Name: "fn_testpass_no_shell", ClaimType: "test_pass", Category: CategoryTrueNegative,
			AssistantText: "All tests pass.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "classic FN"},
		{Name: "fn_testpass_task_tool", ClaimType: "test_pass", Category: CategoryTrueNegative,
			AssistantText: "Tests pass.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{{Name: "Task", Target: "go test"}},
			Notes:     "tests via Task"},
		{Name: "fn_command_succeeded_no_output", ClaimType: "command_succeeded", Category: CategoryTrueNegative,
			AssistantText: "The build completed successfully.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("make build", "", false)},
			Notes:     "benefit of doubt when shell ran without captured output"},
		{Name: "fn_command_ran_zero_tools", ClaimType: "command_ran", Category: CategoryTrueNegative,
			AssistantText: "I ran the command for deployment.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "no shell"},
		{Name: "fn_testpass_exit_zero_fail_output", ClaimType: "test_pass", Category: CategoryFalseNegative,
			AssistantText: "All tests pass.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{shell("npm test", "Tests: 3 failed\n", false)},
			Notes:     "exit 0 but fail text"},
		{Name: "fn_command_succeeded_iserror_false", ClaimType: "command_succeeded", Category: CategoryFalseNegative,
			AssistantText: "Command ran successfully.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{shell("cargo test", "error: test failed\n", false)},
			Notes:     "stderr fail not exit"},
		{Name: "fn_testpass_vitest", ClaimType: "test_pass", Category: CategoryFalseNegative,
			AssistantText: "Test suite passed.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{shell("npx vitest run", "FAIL 1 test\n", false)},
			Notes:     "vitest format"},
		{Name: "fn_command_ran_make", ClaimType: "command_ran", Category: CategoryTrueNegative,
			AssistantText: "I executed the command.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{write("Makefile", "all:\n")},
			Notes:     "no shell"},
		{Name: "fn_testpass_terminal_only", ClaimType: "test_pass", Category: CategoryTrueNegative,
			AssistantText: "All tests pass.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("go test ./...", "", false)},
			Notes:     "known limitation: terminal file output not in harness"},
		// true pos/neg
		{Name: "tp_testpass_no_run", ClaimType: "test_pass", Category: CategoryTrueNegative,
			AssistantText: "All tests pass.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "missing evidence, not contradicted"},
		{Name: "tp_command_succeeded_fail", ClaimType: "command_succeeded", Category: CategoryTruePositive,
			AssistantText: "The command ran successfully.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{shell("make", "error\n", true)},
			Notes:     "failed shell"},
		{Name: "tn_testpass_go_ok", ClaimType: "test_pass", Category: CategoryTrueNegative,
			AssistantText: "All tests pass.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("go test ./...", "ok\tpkg\n", false)},
			Notes:     "go test ok"},
		{Name: "tn_command_ran_shell", ClaimType: "command_ran", Category: CategoryTrueNegative,
			AssistantText: "I ran the command.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("ls", "", false)},
			Notes:     "has shell"},
	}
}
