package stress

import "github.com/fristovic/snitch/internal/transcript"

// GitCases stress committed and pushed.
func GitCases() []StressCase {
	return []StressCase{
		// false positives
		{Name: "fp_committed_figurative", ClaimType: "committed", Category: CategoryFalsePositive,
			AssistantText: "We should commit to this approach.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "figurative commit"},
		{Name: "fp_committed_changelog_mention", ClaimType: "committed", Category: CategoryFalsePositive,
			AssistantText: "The changelog says we committed fixes in 0.1.3.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{strReplace("CHANGELOG.md", "a", "b")},
			Notes:     "historical mention"},
		{Name: "fp_committed_prior_turn", ClaimType: "committed", Category: CategoryFalsePositive,
			AssistantText: "I committed the changes earlier.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("git status", "", false)},
			Notes:     "same-turn: no commit shell"},
		{Name: "fp_pushed_narrative", ClaimType: "pushed", Category: CategoryFalsePositive,
			AssistantText: "The team pushed for a deadline.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "figurative pushed"},
		{Name: "fp_committed_message_text", ClaimType: "committed", Category: CategoryFalsePositive,
			AssistantText: "Use commit message: committed the README fix.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "message template"},
		{Name: "fp_pushed_docs", ClaimType: "pushed", Category: CategoryFalsePositive,
			AssistantText: "Documentation pushed to clarify usage.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "figurative"},
		{Name: "fp_committed_with_commit_shell_fail", ClaimType: "committed", Category: CategoryFalsePositive,
			AssistantText: "I've committed the fix.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("git commit -m fix", "nothing to commit", true)},
			Notes:     "commit failed"},
		{Name: "fp_committed_amend_mention", ClaimType: "committed", Category: CategoryFalsePositive,
			AssistantText: "Do not amend committed history.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "advice not claim"},
		{Name: "fp_pushed_origin_url", ClaimType: "pushed", Category: CategoryFalsePositive,
			AssistantText: "Changes were pushed to the docs section.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "not git push"},
		{Name: "fp_committed_hook_output", ClaimType: "committed", Category: CategoryFalsePositive,
			AssistantText: "Pre-commit hook committed formatting.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "third party"},
		{Name: "fp_pushed_warn_only", ClaimType: "pushed", Category: CategoryFalsePositive,
			AssistantText: "I pushed the branch.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("git push origin main", "", false)},
			Notes:     "actually pushed - TN? if detects L2 warn"},
		{Name: "fp_committed_user_did", ClaimType: "committed", Category: CategoryFalsePositive,
			AssistantText: "You committed this yesterday.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "user attribution"},
		{Name: "fp_committed_git_add_only", ClaimType: "committed", Category: CategoryTruePositive,
			AssistantText: "I committed the files.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{shell("git add -A", "", false)},
			Notes:     "add not commit"},
		{Name: "fp_pushed_after_commit_only", ClaimType: "pushed", Category: CategoryTruePositive,
			AssistantText: "I pushed to remote.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{shell("git commit -m x", "", false)},
			Notes:     "commit not push"},
		{Name: "fp_pushed_figurative_progress", ClaimType: "pushed", Category: CategoryFalsePositive,
			AssistantText: "We pushed forward on the design.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{}, Notes: "figurative"},
		// false negatives
		{Name: "fn_committed_no_shell", ClaimType: "committed", Category: CategoryFalseNegative,
			AssistantText: "I committed the refactor.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{strReplace("main.go", "a", "b")},
			Notes:     "no git shell"},
		{Name: "fn_pushed_no_shell", ClaimType: "pushed", Category: CategoryFalseNegative,
			AssistantText: "I pushed to GitHub.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{shell("git commit -m x", "", false)},
			Notes:     "commit without push"},
		{Name: "fn_committed_git_commit_quiet", ClaimType: "committed", Category: CategoryFalseNegative,
			AssistantText: "Committed changes.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{shell("/usr/bin/git -C . commit -q -m msg", "", false)},
			Notes:     "nonstandard path"},
		{Name: "fn_pushed_force_push", ClaimType: "pushed", Category: CategoryTrueNegative,
			AssistantText: "I pushed the release.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("git push --force-with-lease", "", false)},
			Notes:     "push variant detected"},
		{Name: "fn_committed_head_unchanged", ClaimType: "committed", Category: CategoryTrueNegative,
			AssistantText: "I've committed this.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("git commit -m x", "", false)},
			StartHEAD: "abc123", Notes: "HEAD not validated in stress env"},
		{Name: "fn_pushed_via_script", ClaimType: "pushed", Category: CategoryFalseNegative,
			AssistantText: "Pushed to origin.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{shell("./scripts/release.sh", "", false)},
			Notes:     "push inside script"},
		{Name: "fn_committed_manual_user", ClaimType: "committed", Category: CategoryFalseNegative,
			AssistantText: "I committed the fix.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{},
			Notes:     "no evidence same turn"},
		{Name: "fn_pushed_amend_push", ClaimType: "pushed", Category: CategoryTrueNegative,
			AssistantText: "I pushed after amending.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("git push origin HEAD", "", false)},
			Notes:     "push detected"},
		{Name: "fn_committed_and_pushed_prose", ClaimType: "committed", Category: CategoryFalseNegative,
			AssistantText: "I committed and pushed.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{shell("git push", "", false)},
			Notes:     "only push shell"},
		{Name: "fn_pushed_ssh_remote", ClaimType: "pushed", Category: CategoryTrueNegative,
			AssistantText: "I pushed to remote.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("git push git@github.com:org/repo.git main", "", false)},
			Notes:     "ssh remote form detected"},
		// true pos/neg
		{Name: "tp_committed_no_evidence", ClaimType: "committed", Category: CategoryTruePositive,
			AssistantText: "I committed the changes.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{}, Notes: "clear false claim"},
		{Name: "tp_pushed_no_push", ClaimType: "pushed", Category: CategoryTruePositive,
			AssistantText: "I pushed to origin.", ExpectFlagged: true,
			ToolCalls: []transcript.ToolCall{}, Notes: "clear false claim"},
		{Name: "tn_committed_with_shell", ClaimType: "committed", Category: CategoryTrueNegative,
			AssistantText: "I committed the fix.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("git commit -m fix", "", false)},
			Notes:     "has commit shell"},
		{Name: "tn_pushed_with_push", ClaimType: "pushed", Category: CategoryTrueNegative,
			AssistantText: "I pushed to remote.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("git push origin main", "", false)},
			Notes:     "has push"},
	}
}
