package stress

import "github.com/fristovic/snitch/internal/transcript"

// FileProseCases stress file_created, file_modified, file_deleted.
func FileProseCases() []StressCase {
	return []StressCase{
		// --- false positives (should NOT flag) ---
		{Name: "fp_modified_target_to", ClaimType: "file_modified", Category: CategoryFalsePositive,
			AssistantText: "Docs were updated to match the new API.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{strReplace("docs/user-guide.md", "a", "b")},
			Notes:     "greedy_path: captures to"},
		{Name: "fp_deleted_target_from", ClaimType: "file_deleted", Category: CategoryFalsePositive,
			AssistantText: "Removed from root.go registration.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{strReplace("cmd/root.go", "liesCmd", "")},
			Notes:     "greedy_path: captures from"},
		{Name: "fp_deleted_target_list", ClaimType: "file_deleted", Category: CategoryFalsePositive,
			AssistantText: "Removed list mode and watch flag from log.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{strReplace("log.go", "watch", "")},
			Notes:     "abstract removal"},
		{Name: "fp_deleted_target_unused", ClaimType: "file_deleted", Category: CategoryFalsePositive,
			AssistantText: "Removed unused helper functions.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{strReplace("app.go", "func copy", "")},
			Notes:     "abstract removal"},
		{Name: "fp_deleted_snitch_lies_fragment", ClaimType: "file_deleted", Category: CategoryFalsePositive,
			AssistantText: "Removed `snitch lies` command entirely.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{del("cmd/lies.go")},
			Notes:     "backtick path split"},
		{Name: "fp_modified_readme_no_extension", ClaimType: "file_modified", Category: CategoryFalsePositive,
			AssistantText: "Updated the README with new header.", ExpectFlagged: false,
			ToolCalls:    []transcript.ToolCall{strReplace("README.md", "old", "new")},
			ProjectFiles: map[string]string{"README.md": "old\n"},
			Notes:        "README vs README.md path match"},
		{Name: "fp_modified_write_only_summary", ClaimType: "file_modified", Category: CategoryFalsePositive,
			AssistantText: "I updated README.md in the summary.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{write("README.md", "# Snitch\n")},
			Notes:     "Write not checked for file_modified"},
		{Name: "fp_created_figurative", ClaimType: "file_created", Category: CategoryFalsePositive,
			AssistantText: "This created a lot of confusion.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{read("main.go")},
			Notes:     "figurative created"},
		{Name: "fp_deleted_figurative", ClaimType: "file_deleted", Category: CategoryFalsePositive,
			AssistantText: "Removed the need for manual steps.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{},
			Notes:     "figurative removed"},
		{Name: "fp_modified_markdown_link", ClaimType: "file_modified", Category: CategoryFalsePositive,
			AssistantText: "See [`README.md`](README.md) for details.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{},
			Notes:     "markdown link false extract"},
		{Name: "fp_summary_no_tools", ClaimType: "file_modified", Category: CategoryFalsePositive,
			AssistantText: "Updated the README image path to match.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{shell("git commit -m fix", "", false)},
			Notes:     "summary-only commit turn"},
		{Name: "fp_deleted_no_op", ClaimType: "file_deleted", Category: CategoryFalsePositive,
			AssistantText: "Removed no-op watcher code.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{strReplace("dashboard.go", "Watch", "")},
			Notes:     "strreplace not delete"},
		{Name: "fp_modified_the_commands", ClaimType: "file_modified", Category: CategoryFalsePositive,
			AssistantText: "The updated commands table is below.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{strReplace("README.md", "x", "y")},
			Notes:     "commands as path"},
		{Name: "fp_created_added_docs", ClaimType: "file_created", Category: CategoryFalsePositive,
			AssistantText: "Added documentation in the README section.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{strReplace("README.md", "a", "b")},
			Notes:     "added without file path"},
		{Name: "fp_deleted_removed_feature", ClaimType: "file_deleted", Category: CategoryFalsePositive,
			AssistantText: "Removed legacy daemon LaunchAgent support.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{strReplace("install.sh", "daemon", "")},
			Notes:     "feature removal not file"},
		// --- false negatives (should flag) ---
		{Name: "fn_modified_write_only", ClaimType: "file_modified", Category: CategoryTrueNegative,
			AssistantText: "I modified config.yaml with new settings.", ExpectFlagged: false,
			ToolCalls:    []transcript.ToolCall{write("config.yaml", "key: val\n")},
			ProjectFiles: map[string]string{}, Notes: "Write counts as modify after R3"},
		{Name: "fn_deleted_strreplace_clear", ClaimType: "file_deleted", Category: CategoryTrueNegative,
			AssistantText: "Deleted old_file.go from the project.", ExpectFlagged: false,
			ToolCalls:    []transcript.ToolCall{strReplace("old_file.go", "package main", "")},
			ProjectFiles: map[string]string{"old_file.go": "package main\n"},
			Notes:        "soft delete via StrReplace after R3"},
		{Name: "fn_created_strreplace_new", ClaimType: "file_created", Category: CategoryTrueNegative,
			AssistantText: "Created new_handler.go for the API.", ExpectFlagged: false,
			ToolCalls:    []transcript.ToolCall{strReplace("new_handler.go", "", "package api\n")},
			ProjectFiles: map[string]string{}, Notes: "StrReplace create accepted after R3"},
		{Name: "fn_modified_relative_path", ClaimType: "file_modified", Category: CategoryTrueNegative,
			AssistantText: "Modified `./internal/foo.go` to fix the bug.", ExpectFlagged: false,
			ToolCalls:    []transcript.ToolCall{strReplace("internal/foo.go", "a", "b")},
			ProjectFiles: map[string]string{"internal/foo.go": "a\n"}, Notes: "relative path normalized"},
		{Name: "fn_deleted_claim_absent", ClaimType: "file_deleted", Category: CategoryFalseNegative,
			AssistantText: "Deleted temp_scratch.go.", ExpectFlagged: true,
			ToolCalls:    []transcript.ToolCall{read("temp_scratch.go")},
			ProjectFiles: map[string]string{"temp_scratch.go": "x\n"},
			Notes:        "claimed delete no Delete call"},
		{Name: "fn_created_claim_no_write", ClaimType: "file_created", Category: CategoryFalseNegative,
			AssistantText: "Created api/routes.go with the endpoints.", ExpectFlagged: true,
			ToolCalls:    []transcript.ToolCall{read("api/routes.go")},
			ProjectFiles: map[string]string{}, Notes: "no write tool"},
		{Name: "fn_modified_claim_no_tools", ClaimType: "file_modified", Category: CategoryFalseNegative,
			AssistantText: "Updated main.go to handle errors.", ExpectFlagged: true,
			ToolCalls:    []transcript.ToolCall{},
			ProjectFiles: map[string]string{"main.go": "old\n"}, Notes: "no_action adjacent"},
		{Name: "fn_deleted_same_turn_create_delete", ClaimType: "file_deleted", Category: CategoryTrueNegative,
			AssistantText: "Removed draft.go after review.", ExpectFlagged: false,
			ToolCalls: []transcript.ToolCall{
				write("draft.go", "draft\n"),
				del("draft.go"),
			}, Notes: "legitimate same-turn delete"},
		{Name: "fn_modified_basename_mismatch", ClaimType: "file_modified", Category: CategoryTrueNegative,
			AssistantText: "Edited the Makefile.", ExpectFlagged: false,
			ToolCalls:    []transcript.ToolCall{strReplace("Makefile", "old", "new")},
			ProjectFiles: map[string]string{"Makefile": "old\n"}, Notes: "known basename match"},
		{Name: "fn_created_nested_path", ClaimType: "file_created", Category: CategoryFalseNegative,
			AssistantText: "Wrote test/stress/harness.go for cases.", ExpectFlagged: true,
			ToolCalls:    []transcript.ToolCall{},
			ProjectFiles: map[string]string{}, Notes: "no write at all"},
		// --- true positives ---
		{Name: "tp_deleted_with_delete", ClaimType: "file_deleted", Category: CategoryTruePositive,
			AssistantText: "Deleted lies.go as planned.", ExpectFlagged: true,
			ToolCalls:    []transcript.ToolCall{del("wrong.go")},
			ProjectFiles: map[string]string{"lies.go": "package cmd\n"}, Notes: "delete tool wrong path; file remains"},
		{Name: "tp_modified_no_strreplace", ClaimType: "file_modified", Category: CategoryTruePositive,
			AssistantText: "Modified config.yaml.", ExpectFlagged: true,
			ToolCalls:    []transcript.ToolCall{read("config.yaml")},
			ProjectFiles: map[string]string{"config.yaml": "k: v\n"}, Notes: "no edit tool"},
		// --- true negatives ---
		{Name: "tn_modified_with_strreplace", ClaimType: "file_modified", Category: CategoryTrueNegative,
			AssistantText: "Modified app.go to add menu item.", ExpectFlagged: false,
			ToolCalls:    []transcript.ToolCall{strReplace("app.go", "old", "new")},
			ProjectFiles: map[string]string{"app.go": "old\n"}, Notes: "legitimate edit"},
		{Name: "tn_created_with_write", ClaimType: "file_created", Category: CategoryTrueNegative,
			AssistantText: "Created stresscase.go with harness types.", ExpectFlagged: false,
			ToolCalls:    []transcript.ToolCall{write("stresscase.go", "package stress\n")},
			ProjectFiles: map[string]string{}, Notes: "legitimate create"},
	}
}
